-- drop table TRIP;
-- drop table VEHICLE;



create table VEHICLE (
ID BIGINT(19) PRIMARY KEY,
BEARING int, -- INTEGER(10)
CATEGORY int,
DUID VARCHAR(255) UNIQUE,
GEO_POSITION_STATUS int,
HAS_BIKE_RACK bit,
IS_ACCESSIBLE bit,
IS_DELETED bit,
LAST_MODIFICATION_TIMESTAMP long,
LATITUDE double,
LONGITUDE double,
OPERATIONAL_NUMBER long,
PATTERN_DUID VARCHAR(255),
REFERENCE_TIME Date,
TRIP_DUID VARCHAR(255),
VEHICLE_NUMBER long
);

create table TRIP (
ID long PRIMARY KEY, --BIGINT(19)
DUID VARCHAR(255) UNIQUE,
VEHICLEID long NOT NULL references VEHICLE(id)
);

