-- drop table ROUTE;
-- drop table TRIP;
-- drop table VEHICLE;



create table VEHICLE (
ID BIGINT(19) PRIMARY KEY auto_increment, --BIGINT(19)
BEARING int, -- INTEGER(10)
CATEGORY int,
DUID VARCHAR(255) UNIQUE,
GEO_POSITION_STATUS int,
HAS_BIKE_RACK bit,
IS_ACCESSIBLE bit,
IS_DELETED bit,
LAST_MODIFICATION_TIMESTAMP Date,
LATITUDE double,
LONGITUDE double,
OPERATIONAL_NUMBER long,
PATTERN_DUID VARCHAR(255),
REFERENCE_TIME Date,
TRIP_DUID VARCHAR(255),
VEHICLE_NUMBER long
);

create table TRIP (
ID long PRIMARY KEY auto_increment,
DUID VARCHAR(255) UNIQUE,
VEHICLEID long NOT NULL references VEHICLE(id)
);

create table ROUTE (
ID long PRIMARY KEY auto_increment,
DUID VARCHAR(255) UNIQUE,
LAST_MODIFICATION_TIMESTAMP Date,
IS_DELETED bit,
SHORT_NAME VARCHAR(255),
NUMBER int,
CATEGORY int	
);

create table BUS_STOP_POINT (
ID long PRIMARY KEY auto_increment,
DUID VARCHAR(255) UNIQUE,
NAME VARCHAR(MAX),
LATITUDE double,
LONGITUDE double,
NUMBER int
);